<!DOCTYPE iskola
[
<!ELEMENT iskola (tanar, tantargy)>

<!ELEMENT tanar (nev, szak)>
<!ATTLIST tanar kod ID #REQUIRED>
<!ELEMENT nev (#PCDATA)>
<!ELEMENT szak (#PCDATA)>


<!ATTLIST tantargy kod ID #REQUIRED>
<!ATTLIST tantargy oktato IDREF #REQUIRED>
<!ELEMENT tantargy (tnev, osztaly)>
<!ELEMENT tnev (#PCDATA)>
<!ELEMENT osztaly (#PCDATA)>
]>
<iskola>
    <tanar kod="MM1">
        <nev>Mészaros Máté</nev>
        <szak>GTK</szak>
		
    </tanar>
	<tanar kod ="SZP1">
		<nev>Szabó Péter</nev>
		<szak>GÉIK</szak>
		</tanar>
		
		
	<tantargy tnev ="valami1", osztaly="1B">
		<nev>Valami ora</nev>
		<oktato>Mészaros Máté</oktato>
		<osztaly>1B</osztaly>
		</tantargy>
		
	<tantargy tnev ="valami2", osztaly="2B">
		<nev>Valami ora2</nev>
		<oktato>Szabó Péter</oktato>
		<osztaly>2B</osztaly>
		</tantargy>
		
		
		</iskola>