<?xml version="1.0" encoding ="UTF-8"?>

<!DOCTYPE note
[
   <!ELEMENT note (to,from,heading,body)>
    <!ELEMENT to (#PCDATA)>
    <!ELEMENT from (#PCDATA)>
    <!ELEMENT heading (#PCDATA)>
    <!ELEMENT body (#PCDATA)>
]>
<note>
<to>Péter</to>
<from>Jani</from>
<heading>Emlékeztető</heading>
<body>Ne felejtsd el, amit megbeszéltünk!</body>
</note>
