=== subzerox98415/A5IGRXxmlgyak/XMLFeladatA5igrx/DOMParseA5igrx/XMLSchemaA5igrx.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
<xs:element name="root">
		<xs:complexType>
			<xs:sequence>
<xs:element name="designok" maxOccurs="unbounded">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Design_id">
					<xs:simpleType>
						<xs:restriction base="xs:int">
							<xs:minInclusive value="-2147483648"/>
							<xs:maxInclusive value="2147483647"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="design_név">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="36"/>
							<xs:minLength value="1"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Kép_URL">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="36"/>
							<xs:minLength value="1"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Készítő_neve">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="36"/>
							<xs:minLength value="1"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Használatok_száma">
					<xs:simpleType>
						<xs:restriction base="xs:int">
							<xs:minInclusive value="-2147483648"/>
							<xs:maxInclusive value="2147483647"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Verzioszám">
					<xs:simpleType>
						<xs:restriction base="xs:int">
							<xs:minInclusive value="-2147483648"/>
							<xs:maxInclusive value="2147483647"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				
			</xs:sequence>
		</xs:complexType>
		<xs:key name="designok_PrimaryKey_1">
			<xs:selector xpath="."/>
			<xs:field xpath="Design_id"/>
		</xs:key>
		<xs:keyref name="kész_blokk_design_ForeignKey_1" refer="designok_PrimaryKey_1">
			<xs:selector xpath="kész_blokk_design"/>
			<xs:field xpath="Design_id"/>
		</xs:keyref>
	</xs:element>
<xs:element name="honlap_motor" maxOccurs="unbounded">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Verzioszám">
					<xs:simpleType>
						<xs:restriction base="xs:int">
							<xs:minInclusive value="-2147483648"/>
							<xs:maxInclusive value="2147483647"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Komponens_verziószám">
					<xs:simpleType>
						<xs:restriction base="xs:int">
							<xs:minInclusive value="-2147483648"/>
							<xs:maxInclusive value="2147483647"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				
			</xs:sequence>
		</xs:complexType>
		<xs:key name="honlap_motor_PrimaryKey_1">
			<xs:selector xpath="."/>
			<xs:field xpath="Verzioszám"/>
		</xs:key>
		<xs:keyref name="designok_ForeignKey_1" refer="honlap_motor_PrimaryKey_1">
			<xs:selector xpath="designok"/>
			<xs:field xpath="Verzioszám"/>
		</xs:keyref>
		<xs:keyref name="relationship_ForeignKey_1" refer="honlap_motor_PrimaryKey_1">
			<xs:selector xpath="relationship"/>
			<xs:field xpath="Verzioszám"/>
		</xs:keyref>
	</xs:element>
<xs:element name="kész_blokk_design" maxOccurs="unbounded">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="KBlokkid">
					<xs:simpleType>
						<xs:restriction base="xs:int">
							<xs:minInclusive value="-2147483648"/>
							<xs:maxInclusive value="2147483647"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Blokk_név">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="36"/>
							<xs:minLength value="1"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Melyik_design_rész_blokkja" nillable="true" minOccurs="0">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="36"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Cél_url">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="36"/>
							<xs:minLength value="1"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Design_id" nillable="true" minOccurs="0">
					<xs:simpleType>
						<xs:restriction base="xs:int">
							<xs:minInclusive value="-2147483648"/>
							<xs:maxInclusive value="2147483647"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				
			</xs:sequence>
		</xs:complexType>
		<xs:key name="kész_blokk_design_PrimaryKey_1">
			<xs:selector xpath="."/>
			<xs:field xpath="KBlokkid"/>
		</xs:key>
		<xs:keyref name="kész_blokk_design_emailcím_ForeignKey_1" refer="kész_blokk_design_PrimaryKey_1">
			<xs:selector xpath="kész_blokk_design_emailcím"/>
			<xs:field xpath="KBlokkid"/>
		</xs:keyref>
	</xs:element>
<xs:element name="kész_blokk_design_emailcím" maxOccurs="unbounded">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="emailcím">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="11"/>
							<xs:minLength value="1"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="KBlokkid">
					<xs:simpleType>
						<xs:restriction base="xs:int">
							<xs:minInclusive value="-2147483648"/>
							<xs:maxInclusive value="2147483647"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
		<xs:key name="kész_blokk_design_emailcím_PrimaryKey_1">
			<xs:selector xpath="."/>
			<xs:field xpath="emailcím"/>
			<xs:field xpath="KBlokkid"/>
		</xs:key>
	</xs:element>
<xs:element name="relationship" maxOccurs="unbounded">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Validált" nillable="true" minOccurs="0">
					<xs:simpleType>
						<xs:restriction base="xs:int">
							<xs:minInclusive value="-2147483648"/>
							<xs:maxInclusive value="2147483647"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Verzioszám">
					<xs:simpleType>
						<xs:restriction base="xs:int">
							<xs:minInclusive value="-2147483648"/>
							<xs:maxInclusive value="2147483647"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Widget_ID">
					<xs:simpleType>
						<xs:restriction base="xs:int">
							<xs:minInclusive value="-2147483648"/>
							<xs:maxInclusive value="2147483647"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
		<xs:key name="relationship_PrimaryKey_1">
			<xs:selector xpath="."/>
			<xs:field xpath="Verzioszám"/>
			<xs:field xpath="Widget_ID"/>
		</xs:key>
	</xs:element>
<xs:element name="widgetek" maxOccurs="unbounded">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Widget_ID">
					<xs:simpleType>
						<xs:restriction base="xs:int">
							<xs:minInclusive value="-2147483648"/>
							<xs:maxInclusive value="2147483647"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Widget_neve">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="36"/>
							<xs:minLength value="1"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Használatok_száma">
					<xs:simpleType>
						<xs:restriction base="xs:int">
							<xs:minInclusive value="-2147483648"/>
							<xs:maxInclusive value="2147483647"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Widget_beállítások">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="36"/>
							<xs:minLength value="1"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				
			</xs:sequence>
		</xs:complexType>
		<xs:key name="widgetek_PrimaryKey_1">
			<xs:selector xpath="."/>
			<xs:field xpath="Widget_ID"/>
		</xs:key>
		<xs:keyref name="relationship_ForeignKey_2" refer="widgetek_PrimaryKey_1">
			<xs:selector xpath="relationship"/>
			<xs:field xpath="Widget_ID"/>
		</xs:keyref>
	</xs:element>
	</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== subzerox98415/A5IGRXxmlgyak/XMLFeladatA5igrx/DOMParseA5igrx/XMLA5igrx.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xsi:noNamespaceSchemaLocation="file:///D:/XMLFeladatA5igrx/DOMParseA5igrx/XMLSchemaA5igrx.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<designok>
		<Design_id>1</Design_id>
		<design_név>Fodrászat</design_név>
		<Kép_URL>img55.png</Kép_URL>
		<Készítő_neve>Nyilas Viktor Balázs</Készítő_neve>
		<Használatok_száma>10</Használatok_száma>
		<Verzioszám>1</Verzioszám>
	</designok>
	<designok>
		<Design_id>2</Design_id>
		<design_név>Szépségszalon</design_név>
		<Kép_URL>img33.png</Kép_URL>
		<Készítő_neve>Nyilas Viktor Balázs</Készítő_neve>
		<Használatok_száma>2</Használatok_száma>
		<Verzioszám>1</Verzioszám>
	</designok>
	<designok>
		<Design_id>3</Design_id>
		<design_név>Építkezés</design_név>
		<Kép_URL>img44.png</Kép_URL>
		<Készítő_neve>Nyilas Viktor Balázs</Készítő_neve>
		<Használatok_száma>4</Használatok_száma>
		<Verzioszám>2</Verzioszám>
	</designok>
	<designok>
		<Design_id>4</Design_id>
		<design_név>ÉpítkezésII</design_név>
		<Kép_URL>img45.png</Kép_URL>
		<Készítő_neve>Nyilas Viktor Balázs</Készítő_neve>
		<Használatok_száma>4</Használatok_száma>
		<Verzioszám>2</Verzioszám>
	</designok>
	<designok>
		<Design_id>5</Design_id>
		<design_név>Pizzéria</design_név>
		<Kép_URL>img46.png</Kép_URL>
		<Készítő_neve>Nyilas Viktor Balázs</Készítő_neve>
		<Használatok_száma>4</Használatok_száma>
		<Verzioszám>2</Verzioszám>
	</designok>
	<honlap_motor>
		<Verzioszám>1</Verzioszám>
		<Komponens_verziószám>1</Komponens_verziószám>
	</honlap_motor>
	<honlap_motor>
		<Verzioszám>2</Verzioszám>
		<Komponens_verziószám>2</Komponens_verziószám>
	</honlap_motor>
	<honlap_motor>
		<Verzioszám>3</Verzioszám>
		<Komponens_verziószám>3</Komponens_verziószám>
	</honlap_motor>
	<honlap_motor>
		<Verzioszám>4</Verzioszám>
		<Komponens_verziószám>4</Komponens_verziószám>
	</honlap_motor>
	<honlap_motor>
		<Verzioszám>5</Verzioszám>
		<Komponens_verziószám>5</Komponens_verziószám>
	</honlap_motor>
	<kész_blokk_design>
		<KBlokkid>1</KBlokkid>
		<Blokk_név>D1-01</Blokk_név>
		<Melyik_design_rész_blokkja>D1</Melyik_design_rész_blokkja>
		<Cél_url>img1.png</Cél_url>
		<Design_id>1</Design_id>
	</kész_blokk_design>
	<kész_blokk_design>
		<KBlokkid>2</KBlokkid>
		<Blokk_név>D1-02</Blokk_név>
		<Melyik_design_rész_blokkja>D1</Melyik_design_rész_blokkja>
		<Cél_url>img2.png</Cél_url>
		<Design_id>2</Design_id>
	</kész_blokk_design>
	<kész_blokk_design>
		<KBlokkid>3</KBlokkid>
		<Blokk_név>D1-03</Blokk_név>
		<Melyik_design_rész_blokkja>D1</Melyik_design_rész_blokkja>
		<Cél_url>img3.png</Cél_url>
		<Design_id>3</Design_id>
	</kész_blokk_design>
	<kész_blokk_design>
		<KBlokkid>4</KBlokkid>
		<Blokk_név>D1-04</Blokk_név>
		<Melyik_design_rész_blokkja>D1</Melyik_design_rész_blokkja>
		<Cél_url>img4.png</Cél_url>
		<Design_id>4</Design_id>
	</kész_blokk_design>
	<kész_blokk_design>
		<KBlokkid>5</KBlokkid>
		<Blokk_név>D1-05</Blokk_név>
		<Melyik_design_rész_blokkja>D1</Melyik_design_rész_blokkja>
		<Cél_url>img5.png</Cél_url>
		<Design_id>5</Design_id>
	</kész_blokk_design>
	<kész_blokk_design_emailcím>
		<emailcím>a@b.com</emailcím>
		<KBlokkid>1</KBlokkid>
	</kész_blokk_design_emailcím>
	<kész_blokk_design_emailcím>
		<emailcím>b@a.com</emailcím>
		<KBlokkid>2</KBlokkid>
	</kész_blokk_design_emailcím>
	<kész_blokk_design_emailcím>
		<emailcím>c@b.com</emailcím>
		<KBlokkid>4</KBlokkid>
	</kész_blokk_design_emailcím>
	<relationship>
		<Validált>1</Validált>
		<Verzioszám>1</Verzioszám>
		<Widget_ID>1</Widget_ID>
	</relationship>
	<relationship>
		<Validált>1</Validált>
		<Verzioszám>1</Verzioszám>
		<Widget_ID>3</Widget_ID>
	</relationship>
	<relationship>
		<Validált>0</Validált>
		<Verzioszám>2</Verzioszám>
		<Widget_ID>5</Widget_ID>
	</relationship>
	<widgetek>
		<Widget_ID>1</Widget_ID>
		<Widget_neve>IconBox</Widget_neve>
		<Használatok_száma>340</Használatok_száma>
		<Widget_beállítások>Eltartás10Hatterszürke</Widget_beállítások>
	</widgetek>
	<widgetek>
		<Widget_ID>2</Widget_ID>
		<Widget_neve>SzövegBox</Widget_neve>
		<Használatok_száma>600</Használatok_száma>
		<Widget_beállítások>Eltartás10Hatternone</Widget_beállítások>
	</widgetek>
	<widgetek>
		<Widget_ID>3</Widget_ID>
		<Widget_neve>KombiBox</Widget_neve>
		<Használatok_száma>140</Használatok_száma>
		<Widget_beállítások>Eltartás10Hatterfekete</Widget_beállítások>
	</widgetek>
	<widgetek>
		<Widget_ID>4</Widget_ID>
		<Widget_neve>MegosztásFacebook</Widget_neve>
		<Használatok_száma>20</Használatok_száma>
		<Widget_beállítások>Eltartás10Hatterzöld</Widget_beállítások>
	</widgetek>
	<widgetek>
		<Widget_ID>5</Widget_ID>
		<Widget_neve>MegosztásTwitter</Widget_neve>
		<Használatok_száma>10</Használatok_száma>
		<Widget_beállítások>Eltartás10Hatterpink</Widget_beállítások>
	</widgetek>
</root>
